name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [24.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install npm
      run: npm install
    - name: Install Playwright
      run: npm install playwright@latest
    - name: Install Playwright BDD
      run: npm install playwright-bdd
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Cucumber
      run: npm i @cucumber/cucumber -D
    - name: Install ts-node
      run: npm i ts-node -D
    - name: Install Dotenv
      run: npm install dotenv
    - name: Install Cucumber Report
      run: npm i multiple-cucumber-html-reporter -D
    - name: Install winston
      run: npm i winston
    - name: Generate test files from feature files
      run: npm run bddgen
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results
        retention-days: 1
